apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: compose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: web-server
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: compose convert -f docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: web-server
    spec:
      containers:
        - image: ulyaulya/php
          name: web-server
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
