apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: compose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: web-server
  name: web-server
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: web-server
status:
  loadBalancer: {}
